### ISSUE TITLE
[Migration] Create a directory, config, and icon for each "integration"

### ISSUE THREAD

**Issue by zstix** [newrelic/newrelic-observability-packs#128]
## Description
We would like to migrate all of the _integrations_ from [newrelic.com/integrations](https://newrelic.com/integrations) into packs in the repository. Each should have it's own directory with a configuration YAML and the icon. Where applicable, related _integrations_ can be grouped under new sub-directories. For example, all AWS _integrations_ can go under an `aws` directory within the `packs` directory.

**! See the internal Epic Doc for a link to a spreadsheet with detailed information on folder hierarchy**

Here's an example of how the directory structure should look:

```
newrelic-observability-packs
  |  packs
  |  |  apache
  |  |  |  config.yml
  |  |  |  logo.png
  |  |  aws
  |  |  |  aws-cloudfront
  |  |  |  |  config.yml
  |  |  |  |  logo.png
```

There are: 
 - **368** new _integration_ packs
 - Of which **292** can be grouped under sub-directories
 - **24** new sub-directories a la `aws`
 -  Refer to the spreadsheet on `G-Drive` called `Integrations as observability packs` for more details

The data that drives [newrelic.com/integrations](https://newrelic.com/integrations) can be accessed from [this JSON endpoint](https://live-d9newrelic.pantheonsite.io/content-api/v1/integrations).

The relevant details of the JSON are:

```json
attributes: {
    title: "AWS NLB/ALB",
    field_integration__description: "Distributes incoming application traffic across multiple targets, such as EC2 instances, in multiple availability zones.",
    field_integration__docs_link: "https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws- albnlb-monitoring-integration",
}
```

The `config.yml` should look like this, populated with the relevant `attributes` from the JSON endpoint:

```yaml
name: ${{ title }} from newrelic.com/integration
description: ${{ field_integration__description }} from newrelic.com/integrations
logo: logo-from-newreilc-integrations.png

documentation:
  - name: ${{ title }} installation docs
    description: ${{ field_integration__description }} from newrelic.com/integrations
    url: ${{ field_integration__docs_link }}
```
The `name` parameter under `documentation` should be set to `$title installation docs`

## Acceptance Criteria
We will need to create a script that achieves the following acceptance criteria:
* [x] Create a new pack for every item on newrelic.com/integrations
* [x] Related **_integration packs_** should be grouped under a sub-directory where applicable (e.g. an `aws` directory should contain all AWS **_integration packs_**)
* [x] Each pack should have a `config.yml` file containing the _name_, _logo_, _description_, and _documentation_
* [x] The logo should be downloaded from the JSON API and saved separately as both the `icon` and `logo` for the pack
