### ISSUE TITLE
[Migration] Add a reference to documentation for packs currently in the repo

### ISSUE THREAD

**Issue by zstix** [newrelic/newrelic-observability-packs#129]
## Description
Once we have migrated the content from [newrelic.com/integrations](https://newrelic.com/integrations) (#128), we should check for any overlap between **_integration_** packs and packs that already exist in the catalog.  For example, we have a PHP pack and a PHP **_integration_**. 

Existing packs should be augmented with the documentation details from newly created **_integration_** packs, which should then be removed.

**! See the internal Epic Doc for a link to a spreadsheet with detailed information existing QuickStarts that can be augmented**

This can be done by updating the `config.yml` for each Pack and adding in a `documentation` field:

```yml
name: PHP
description: ...
level: New Relic

Author: ...

# addition
documentation:
    url: https://docs.newrelic.com/php
    description: This is for PHP
    name: Get started with PHP
```

Since there's only `19` existing Packs that can be augmented with documentation, this can probably be done by hand (rather than creating a script).

## Acceptance Criteria
* [x] https://github.com/newrelic/newrelic-observability-packs/issues/128
* [x] Review each pack currently in the catalog (This has been done in the spreadsheet referenced)
* [x] Augment existing packs with documentation details from duplicate **_integration_** packs
* [x] Remove the duplicate **_integration_** packs from the repo
