### ISSUE TITLE
[Migration] Update repository automation to account for instrumentation

### ISSUE THREAD

**Issue by zstix** [newrelic/newrelic-observability-packs#130]
## Description
Once we've migrated the content from [newrelic.com/integrations](https://newrelic.com/integrations) (#128), we should adjust our PR validation to account for the new fields. Specifically, we should allow for an optional field (`instrumentation`) that accepts an array of objects (each with a `type` and `url`).

At the moment, we only have `documentation`, but we will probably want additional types for things like `agent`.

```yml
name: PHP
description: ...
level: New Relic

Author: ...

# addition
instrumentation:
  - type: documentation
    url: /instrumentation/php
```

The [pack config file schema spec](https://github.com/newrelic/newrelic-observability-packs/blob/main/docs/config-spec.md) has an `instrumentation` field that we would be leveraging.

## Acceptance Criteria
* [x] https://github.com/newrelic/newrelic-observability-packs/issues/128
* [ ] Add a validity check for `instrumentation` (when applicable)
